### ISSUE TITLE
Add data for opioids during pregnancy

### ISSUE THREAD

**Issue by HealthAnalyticsResearchPolicy** [DurhamRegionHARP/RRFSS-data-explorer#7]
This is a new module not included on the original list. @jasanthanaidoo has run the module through STATA and it needs to be included on the site.

**Comment by lanejames35** [comment]
Modified the SAS program and update the CSV files. Waiting for @jasanthanaidoo to review. See screen shots below.
![image](https://user-images.githubusercontent.com/17464914/69828609-761f3e80-11ea-11ea-870a-c95e399d719e.png)

**Comment by lanejames35** [comment]
The estimates above excluded "Don't know" from denominator. Ran the analysis again with full sample in the denominator.

**Comment by HealthAnalyticsResearchPolicy** [comment]
Estimates reviewed and approved by @jasanthanaidoo. Going to merge this branch.
